# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-30 12:29
from __future__ import unicode_literals

import DjangoUeditor.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [

        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='博客标题')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='博客标签')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='博客正文')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
